### ISSUE TITLE
No drives detected on packaged Ubuntu

### ISSUE THREAD

**Issue by jviotti** [resin-io/herostratus#35]
I get the following on Ubuntu:

```sh
Unhandled rejection Error: Command failed: /bin/sh -c "/home/jviotti/Desktop/Herostratus-linux-x64/resources/app.asar/node_modules/drivelist/scripts"/linux.sh
/bin/sh: 1: /home/jviotti/Desktop/Herostratus-linux-x64/resources/app.asar/node_modules/drivelist/scripts/linux.sh: not found

    at ChildProcess.exithandler (child_process.js:209:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Drivelist executes scripts as child processes to discover the drives, however the fact that everything is packaged into an `asar` makes the scripts inaccessible.

This is probably the same issue as https://github.com/resin-io/herostratus/issues/28

**Comment by jviotti** [comment]
Also the same as https://github.com/resin-io/herostratus/issues/18.

We have to find a solution, since omitting `--asar` might not be possible on Windows due to long file paths in `node_modules/`.

**Comment by jviotti** [comment]
This being fixed in https://github.com/atom/electron/pull/3595.
